apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-user
  name: backend-user
  namespace: default
  selfLink: /api/v1/namespaces/default/services/backend-user
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    service: backend-user